server:
  port: 7005
#Eureka的配置
eureka:
  instance:
    hostname: eureka7005.com #eureka服务端的实例名称,记得要在hosts文件或者修改真实的dns解析
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务,客户端该处是不是应该为true呢
    service-url:
      #控制中心  本例中可以访问控制台监控
      #单机使用如下形式
      #      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群采用如下形式,每个服务注册中心和其他中心相关联
      defaultZone: http://eureka7004.com:7004/eureka/,http://eureka7006.com:7006/eureka/